/**
 * 
 */
package com.guzzservices.manager.impl.ip;

import java.util.HashMap;
import java.util.Map;

import org.guzz.util.StringUtil;

/**
 * 
 * 
 * 
 * @author liukaixuan(liukaixuan@gmail.com)
 */
public class CleanUtil {
	
	private static String[] czNames = new String[]{"CZ888", "IANA", "纯真网络", "局域网", "未分配", "本机地址", "未知物理地址", "中国", "局域网", "非公网地址", "全国"} ;
	
	private static Map<String, String> ipMarkers = new HashMap<String, String>() ;
	
	public static String escapeCZ(String name){
		if(StringUtil.isEmpty(name)) return null ;
		
		for(String s : czNames){
			if(name.equalsIgnoreCase(s)){
				return null ;
			}
		}
		
		return name ;
	}
	
	public static String getCityMarker(String cityName){
		return ipMarkers.get(cityName) ;
	}
	
	static{
		ipMarkers.put("美国"                 , "海外") ;
		ipMarkers.put("日本"                 , "海外") ;
		ipMarkers.put("英国"                 , "海外") ;
		                           
		ipMarkers.put("马来西亚"             , "海外") ;
		ipMarkers.put("巴基斯坦"             , "海外") ;
		ipMarkers.put("新西兰"               , "海外") ;
		ipMarkers.put("韩国"                 , "海外") ;
		ipMarkers.put("泰国"                 , "海外") ;
		ipMarkers.put("孟加拉国"             , "海外") ;
		ipMarkers.put("印度尼西亚"           , "海外") ;
		ipMarkers.put("印度"                 , "海外") ;
		ipMarkers.put("菲律宾"               , "海外") ;
		ipMarkers.put("新加坡"               , "海外") ;
		ipMarkers.put("APNIC"                , "海外") ;
		ipMarkers.put("阿富汗"               , "海外") ;
		ipMarkers.put("越南"                 , "海外") ;
		ipMarkers.put("新喀里多尼亚"         , "海外") ;
		ipMarkers.put("文莱"                 , "海外") ;
		ipMarkers.put("亚太地区网络"         , "海外") ;
		ipMarkers.put("以色列"               , "海外") ;
		ipMarkers.put("希腊"                 , "海外") ;
		ipMarkers.put("瑞士"                 , "海外") ;
		ipMarkers.put("沙特阿拉伯"           , "海外") ;
		ipMarkers.put("瑞典"                 , "海外") ;
		ipMarkers.put("波兰"                 , "海外") ;
		ipMarkers.put("法国"                 , "海外") ;
		ipMarkers.put("黑山共和国"           , "海外") ;
		ipMarkers.put("德国"                 , "海外") ;
		ipMarkers.put("捷克"                 , "海外") ;
		ipMarkers.put("比利时"               , "海外") ;
		ipMarkers.put("俄罗斯"               , "海外") ;
		ipMarkers.put("肯尼亚"               , "海外") ;
		ipMarkers.put("爱尔兰"               , "海外") ;
		ipMarkers.put("意大利"               , "海外") ;
		ipMarkers.put("荷兰"                 , "海外") ;
		ipMarkers.put("丹麦"                 , "海外") ;
		ipMarkers.put("塞浦路斯"             , "海外") ;
		ipMarkers.put("埃及"                 , "海外") ;
		ipMarkers.put("奥地利"               , "海外") ;
		ipMarkers.put("西班牙"               , "海外") ;
		ipMarkers.put("乌克兰"               , "海外") ;
		ipMarkers.put("塔吉克斯坦"           , "海外") ;
		ipMarkers.put("乌兹别克斯坦"         , "海外") ;
		ipMarkers.put("挪威"                 , "海外") ;
		ipMarkers.put("土耳其"               , "海外") ;
		ipMarkers.put("白俄罗斯"             , "海外") ;
		ipMarkers.put("格鲁吉亚"             , "海外") ;
		ipMarkers.put("乌苏里"               , "海外") ;
		ipMarkers.put("保加利亚"             , "海外") ;
		ipMarkers.put("芬兰"                 , "海外") ;
		ipMarkers.put("葡萄牙"               , "海外") ;
		ipMarkers.put("马达加斯加"           , "海外") ;
		ipMarkers.put("伊朗"                 , "海外") ;
		ipMarkers.put("阿曼"                 , "海外") ;
		ipMarkers.put("阿尔及利亚"           , "海外") ;
		ipMarkers.put("拉脱维亚"             , "海外") ;
		ipMarkers.put("爱沙尼亚"             , "海外") ;
		ipMarkers.put("斯洛伐克"             , "海外") ;
		ipMarkers.put("利比亚"               , "海外") ;
		ipMarkers.put("约旦"                 , "海外") ;
		ipMarkers.put("匈牙利"               , "海外") ;
		ipMarkers.put("科威特"               , "海外") ;
		ipMarkers.put("欧洲"                 , "海外") ;
		ipMarkers.put("立陶宛"               , "海外") ;
		ipMarkers.put("哈萨克斯坦"           , "海外") ;
		                           
		ipMarkers.put("江西"                 , "江西") ;
		ipMarkers.put("广西"                 , "广西") ;
		ipMarkers.put("香港"                 , "香港") ;
		ipMarkers.put("黑龙江"             , "黑龙江") ;
		ipMarkers.put("新疆"                 , "新疆") ;
		ipMarkers.put("对外经济贸易大学"     , "北京") ;
		ipMarkers.put("华中农业大学"         , "湖北") ;
		ipMarkers.put("吉林"                 , "吉林") ;
		ipMarkers.put("厦门大学"             , "福建") ;
		ipMarkers.put("厦门大学漳州"         , "福建") ;
		ipMarkers.put("上海"                 , "上海") ;
		ipMarkers.put("宁波大学"             , "浙江") ;
		ipMarkers.put("新疆伊犁州"           , "新疆") ;
		ipMarkers.put("新疆博尔塔拉州"       , "新疆") ;
		ipMarkers.put("浙江"                 , "浙江") ;
		ipMarkers.put("清华大学"             , "北京") ;
		ipMarkers.put("长江大学"             , "湖北") ;
		ipMarkers.put("重庆"                 , "重庆") ;
		ipMarkers.put("华东师范大学"         , "上海") ;
		ipMarkers.put("合肥"                 , "安徽") ;
		ipMarkers.put("宁夏"                 , "宁夏") ;
		ipMarkers.put("汉中理工学院"         , "陕西") ;
		ipMarkers.put("云南"                 , "云南") ;
		ipMarkers.put("成都信息工程学院"     , "四川") ;
		ipMarkers.put("兰州"                 , "甘肃") ;
		ipMarkers.put("佳木斯大学"         , "黑龙江") ;
		ipMarkers.put("湖北"                 , "湖北") ;
		ipMarkers.put("华中科技大学"         , "湖北") ;
		ipMarkers.put("西安科技大学"         , "陕西") ;
		ipMarkers.put("西安外事学院"         , "陕西") ;
		ipMarkers.put("西安思源学院"         , "陕西") ;
		ipMarkers.put("湖南"                 , "湖南") ;
		ipMarkers.put("四川"                 , "四川") ;
		ipMarkers.put("贵州"                 , "贵州") ;
		ipMarkers.put("安徽"                 , "安徽") ;
		ipMarkers.put("新疆昌吉州"           , "新疆") ;
		ipMarkers.put("华东交通大学"         , "上海") ;
		ipMarkers.put("罗马尼亚"             , "海外") ;
		ipMarkers.put("黎巴嫩"               , "海外") ;
		ipMarkers.put("亚美尼亚"             , "海外") ;
		ipMarkers.put("塞尔维亚"             , "海外") ;
		ipMarkers.put("冰岛"                 , "海外") ;
		ipMarkers.put("马其顿"               , "海外") ;
		ipMarkers.put("马耳他"               , "海外") ;
		ipMarkers.put("尼日利亚"             , "海外") ;
		ipMarkers.put("RIPE"                 , "海外") ;
		ipMarkers.put("南非"                 , "海外") ;
		ipMarkers.put("伊拉克"               , "海外") ;
		ipMarkers.put("巴林"                 , "海外") ;
		ipMarkers.put("阿塞拜疆"             , "海外") ;
		ipMarkers.put("直布罗陀"             , "海外") ;
		ipMarkers.put("摩尔多瓦"             , "海外") ;
		ipMarkers.put("卢森堡"               , "海外") ;
		ipMarkers.put("摩纳哥"               , "海外") ;
		ipMarkers.put("摩洛哥"               , "海外") ;
		ipMarkers.put("波多黎各"             , "海外") ;
		ipMarkers.put("加拿大"               , "海外") ;
		ipMarkers.put("联合国"               , "海外") ;
		ipMarkers.put("洪都拉斯"             , "海外") ;
		ipMarkers.put("特立尼达和多巴哥"     , "海外") ;
		ipMarkers.put("多米尼加共和国"       , "海外") ;
		ipMarkers.put("海地"                 , "海外") ;
		ipMarkers.put("安地瓜"               , "海外") ;
		ipMarkers.put("巴哈马"               , "海外") ;
		ipMarkers.put("巴巴多斯"             , "海外") ;
		ipMarkers.put("汤加"                 , "海外") ;
		ipMarkers.put("马绍尔群岛"           , "海外") ;
		ipMarkers.put("圭亚那"               , "海外") ;
		ipMarkers.put("特克斯和凯科斯群岛"   , "海外") ;
		ipMarkers.put("牙买加"               , "海外") ;
		ipMarkers.put("阿根廷"               , "海外") ;
		ipMarkers.put("安哥拉"               , "海外") ;
		ipMarkers.put("乌拉圭"               , "海外") ;
		ipMarkers.put("ARIN"                 , "海外") ;
		ipMarkers.put("Teleglobe"            , "海外") ;
		ipMarkers.put("朝鲜"                 , "海外") ;
		ipMarkers.put("开曼群岛"             , "海外") ;
		ipMarkers.put("安提瓜岛"             , "海外") ;
		ipMarkers.put("斯洛文尼亚"           , "海外") ;
		ipMarkers.put("叙利亚"               , "海外") ;
		ipMarkers.put("波黑"                 , "海外") ;
		ipMarkers.put("克罗地亚"             , "海外") ;
		ipMarkers.put("吉尔吉斯斯坦"         , "海外") ;
		ipMarkers.put("阿尔巴尼亚"           , "海外") ;
		ipMarkers.put("圣马力诺"             , "海外") ;
		ipMarkers.put("卡塔尔"               , "海外") ;
		ipMarkers.put("中东及欧洲地区"       , "海外") ;
		ipMarkers.put("毛里求斯"             , "海外") ;
		ipMarkers.put("列支敦士登"           , "海外") ;
		ipMarkers.put("捷克共和国"           , "海外") ;
		ipMarkers.put("法罗群岛"             , "海外") ;
		ipMarkers.put("加纳"                 , "海外") ;
		ipMarkers.put("AFRINIC"              , "海外") ;
		ipMarkers.put("阿联酋"               , "海外") ;
		ipMarkers.put("多哥"                 , "海外") ;
		ipMarkers.put("土尔其"               , "海外") ;
		ipMarkers.put("贝宁"                 , "海外") ;
		ipMarkers.put("澳门"                 , "澳门") ;
		ipMarkers.put("布隆迪"               , "海外") ;
		ipMarkers.put("喀麦隆"               , "海外") ;
		ipMarkers.put("乌干达"               , "海外") ;
		ipMarkers.put("坦桑尼亚"             , "海外") ;
		ipMarkers.put("赞比亚"               , "海外") ;
		ipMarkers.put("刚果"                 , "海外") ;
		ipMarkers.put("巴勒斯坦"             , "海外") ;
		ipMarkers.put("也门"                 , "海外") ;
		ipMarkers.put("毛里塔尼亚"           , "海外") ;
		ipMarkers.put("阿拉伯联合酋长国"     , "海外") ;
		ipMarkers.put("委内瑞拉"             , "海外") ;
		ipMarkers.put("英格兰"               , "海外") ;
		ipMarkers.put("罗马尼亚布"           , "海外") ;
		ipMarkers.put("北美地区"             , "海外") ;
		ipMarkers.put("欧洲和中东地区"       , "海外") ;
		ipMarkers.put("西萨摩亚"             , "海外") ;
		ipMarkers.put("尼泊尔"               , "海外") ;
		ipMarkers.put("柬埔寨"               , "海外") ;
		ipMarkers.put("亚太地区"             , "海外") ;
		ipMarkers.put("关岛"                 , "海外") ;
		ipMarkers.put("孟加拉"               , "海外") ;
		ipMarkers.put("斯里兰卡"             , "海外") ;
		ipMarkers.put("瓦努阿图"             , "海外") ;
		ipMarkers.put("斐济"                 , "海外") ;
		ipMarkers.put("印尼"                 , "海外") ;
		ipMarkers.put("老挝"                 , "海外") ;
		ipMarkers.put("西藏"                 , "海外") ;
		ipMarkers.put("瓦利斯和富图纳群岛"   , "海外") ;
		ipMarkers.put("巴布亚新几内亚"       , "海外") ;
		ipMarkers.put("蒙古"                 , "海外") ;
		ipMarkers.put("Equinix"              , "海外") ;
		ipMarkers.put("法属玻利尼西亚"       , "海外") ;
		ipMarkers.put("马尔代夫"             , "海外") ;
		ipMarkers.put("新疆博州"             , "新疆") ;
		ipMarkers.put("Yahoo"                , "海外") ;
		ipMarkers.put("密克罗尼西亚"         , "海外") ;
		ipMarkers.put("新疆巴音郭楞州"       , "新疆") ;
		ipMarkers.put("Microsoft"            , "海外") ;
		ipMarkers.put("意大利"              , "海外") ;
		ipMarkers.put("墨西哥"               , "海外") ;
		ipMarkers.put("巴西"                 , "海外") ;
		ipMarkers.put("台湾"                 , "台湾") ;
		ipMarkers.put("瑞士"                , "海外") ;
		ipMarkers.put("智利"                 , "海外") ;
		ipMarkers.put("REPUBLIC"             , "海外") ;
		ipMarkers.put("厄瓜多尔"             , "海外") ;
		ipMarkers.put("哥伦比亚"             , "海外") ;
		ipMarkers.put("塞尔维亚和黑山"       , "海外") ;
		ipMarkers.put("秘鲁"                 , "海外") ;
		ipMarkers.put("哥斯达黎加"           , "海外") ;
		ipMarkers.put("马来西"               , "海外") ;
		ipMarkers.put("尼加拉瓜"             , "海外") ;
		ipMarkers.put("玻利维亚"             , "海外") ;
		ipMarkers.put("博茨瓦纳"             , "海外") ;
		ipMarkers.put("危地马拉"             , "海外") ;
		ipMarkers.put("萨尔瓦多"             , "海外") ;
		ipMarkers.put("古巴"                 , "海外") ;
		ipMarkers.put("拉美地区"             , "海外") ;
		ipMarkers.put("多米泥加共和国"       , "海外") ;
		ipMarkers.put("突尼斯"               , "海外") ;
		ipMarkers.put("塞内加尔"             , "海外") ;
		ipMarkers.put("布基纳法索"           , "海外") ;
		ipMarkers.put("尼日尔"               , "海外") ;
		ipMarkers.put("法属玻里尼西"         , "海外") ;
		ipMarkers.put("梵蒂冈"               , "海外") ;
		ipMarkers.put("BITS国"               , "海外") ;
		ipMarkers.put("瓜德罗普岛"           , "海外") ;
		ipMarkers.put("津巴布韦"             , "海外") ;
		ipMarkers.put("象牙海岸"             , "海外") ;
		ipMarkers.put("吉布提"               , "海外") ;
		ipMarkers.put("乍得"                 , "海外") ;
		ipMarkers.put("中非"                 , "海外") ;
		ipMarkers.put("东萨摩亚"             , "海外") ;
		ipMarkers.put("莫桑比克"             , "海外") ;
		ipMarkers.put("几内亚比绍"           , "海外") ;
		ipMarkers.put("斯威士兰"             , "海外") ;
		ipMarkers.put("土库曼斯坦"           , "海外") ;
		ipMarkers.put("德国"                , "海外") ;
		ipMarkers.put("百慕大"               , "海外") ;
		ipMarkers.put("纳米比亚"             , "海外") ;
		ipMarkers.put("多米尼加"             , "海外") ;
		ipMarkers.put("留尼汪岛"             , "海外") ;
		ipMarkers.put("安道尔"               , "海外") ;
		ipMarkers.put("塞拉利昂"             , "海外") ;
		ipMarkers.put("格陵兰群岛"           , "海外") ;
		ipMarkers.put("佛得角"               , "海外") ;
		ipMarkers.put("圣多美和普林"         , "海外") ;
		ipMarkers.put("卢旺达"               , "海外") ;
		ipMarkers.put("加蓬"                 , "海外") ;
		ipMarkers.put("比利时"              , "海外") ;
		ipMarkers.put("科摩罗"               , "海外") ;
		ipMarkers.put("挪威"                , "海外") ;
		ipMarkers.put("索马里"               , "海外") ;
		ipMarkers.put("苏丹"                 , "海外") ;
		ipMarkers.put("马里"                 , "海外") ;
		ipMarkers.put("非洲地区"             , "海外") ;
		ipMarkers.put("美国"                , "海外") ;
		ipMarkers.put("LACNIC"               , "海外") ;
		ipMarkers.put("特立尼和多巴哥"       , "海外") ;
		ipMarkers.put("伯利兹"               , "海外") ;
		ipMarkers.put("苏里南"               , "海外") ;
		ipMarkers.put("百慕大群岛"           , "海外") ;
		ipMarkers.put("巴拉圭"               , "海外") ;
		ipMarkers.put("所罗门群岛"           , "海外") ;
		ipMarkers.put("图瓦卢"               , "海外") ;
		ipMarkers.put("雅虎"                 , "北京") ;
		ipMarkers.put("法属玻利尼西"         , "海外") ;
		ipMarkers.put("萨摩亚"               , "海外") ;
		ipMarkers.put("基里巴斯"             , "海外") ;
		ipMarkers.put("文莱达鲁萨兰"         , "海外") ;
		ipMarkers.put("华南理工大学"         , "广东") ;
		ipMarkers.put("雅虎亚洲网络"         , "北京") ;
		ipMarkers.put("英属印度洋"           , "海外") ;
		ipMarkers.put("艾提宽带(北京"        , "北京") ;
		ipMarkers.put("纽埃"                 , "海外") ;
		ipMarkers.put("美属萨摩亚"           , "海外") ;
		                           
		ipMarkers.put("Intelsat公司"         , "海外") ;
		                           
		ipMarkers.put("塞舌尔"               , "海外") ;
		ipMarkers.put("东帝汶"               , "海外") ;
		ipMarkers.put("托克劳群岛"           , "海外") ;
		ipMarkers.put("瑙鲁"                 , "海外") ;
		ipMarkers.put("北马里亚纳群岛"       , "海外") ;
		ipMarkers.put("不丹"                 , "海外") ;
		ipMarkers.put("法属波利尼西亚"       , "海外") ;
		ipMarkers.put("华东理工大学"         , "上海") ;
		ipMarkers.put("东华理工大学"         , "江西") ;
		ipMarkers.put("IBM中国"              , "北京") ;
		ipMarkers.put("南开大学"             , "天津") ;
		ipMarkers.put("武汉大学"             , "湖北") ;
		ipMarkers.put("西华大学"             , "四川") ;
		ipMarkers.put("中山大学"             , "广东") ;
		ipMarkers.put("华南农业大学"         , "广东") ;
		ipMarkers.put("西安交通大学"         , "陕西") ;
		ipMarkers.put("大连理工大学"         , "山东") ;
		ipMarkers.put("哈尔滨工程大学"     , "黑龙江") ;
		ipMarkers.put("哈尔滨理工大学"     , "黑龙江") ;
		ipMarkers.put("东北林业大学"       , "黑龙江") ;
		ipMarkers.put("东南大学"             , "江苏") ;
		ipMarkers.put("南京大学"             , "江苏") ;
		ipMarkers.put("东华大学"             , "上海") ;
		ipMarkers.put("同济大学"             , "上海") ;
		ipMarkers.put("帕劳"                 , "海外") ;
		ipMarkers.put("Heartlandis"          , "海外") ;
		ipMarkers.put("澳洲"                 , "海外") ;
		ipMarkers.put("雅虎中国"             , "北京") ;
		ipMarkers.put("Equinix亚太公司"      , "北京") ;
		ipMarkers.put("郑州"                 , "河南") ;
		ipMarkers.put("大庆职工大学"       , "黑龙江") ;
		ipMarkers.put("长春工业大学"         , "吉林") ;
		ipMarkers.put("西安石油大学"         , "陕西") ;
		ipMarkers.put("北方工业大学"         , "北京") ;
		ipMarkers.put("首都经贸大学"         , "北京") ;
		ipMarkers.put("首都师范大学"         , "北京") ;
		ipMarkers.put("Firebrand"            , "海外") ;
		ipMarkers.put("诺福克岛"             , "海外") ;
		ipMarkers.put("缅甸"                 , "海外") ;
		ipMarkers.put("AsiaNetcom公司"       , "海外") ;
		ipMarkers.put("维多利亚"             , "海外") ;
		ipMarkers.put("新喀里多尼亚岛"       , "海外") ;
		ipMarkers.put("中经网"               , "北京") ;
		ipMarkers.put("Sprint亚太地区网络"   , "海外") ;
		ipMarkers.put("Concert亚太区网络"    , "海外") ;
		ipMarkers.put("青海"                 , "青海") ;
		ipMarkers.put("乌鲁木齐"             , "新疆") ;
		ipMarkers.put("福建"                 , "福建") ;
		ipMarkers.put("福州"                 , "福建") ;
		ipMarkers.put("集美大学"             , "福建") ;
		ipMarkers.put("齐齐哈尔医学院"     , "黑龙江") ;
		ipMarkers.put("UUNET亚太区网络"      , "北京") ;
		ipMarkers.put("成都工业学院"         , "四川") ;
		ipMarkers.put("南京理工大学"         , "江苏") ;
		ipMarkers.put("长春职业技术学院"     , "吉林") ;
		ipMarkers.put("首都科技大学"         , "北京") ;
		ipMarkers.put("武汉通讯指挥学校"     , "湖北") ;
		ipMarkers.put("沙特阿拉伯Ummul"      , "海外") ;
		ipMarkers.put("沙特阿拉伯UKing"      , "海外") ;
		ipMarkers.put("西班牙"              , "海外") ;
		ipMarkers.put("冈比亚"               , "海外") ;
		ipMarkers.put("安提瓜和巴布"         , "海外") ;
		ipMarkers.put("埃塞俄比亚"           , "海外") ;
		ipMarkers.put("科特迪瓦"             , "海外") ;
		ipMarkers.put("丹麦"                , "海外") ;
		ipMarkers.put("马提尼克岛"           , "海外") ;
		ipMarkers.put("厄立特里亚"           , "海外") ;
		ipMarkers.put("英国"                , "海外") ;
		ipMarkers.put("奥地利"              , "海外") ;
		ipMarkers.put("塞浦路斯"            , "海外") ;
		ipMarkers.put("埃及"                , "海外") ;
		ipMarkers.put("罗马利亚"             , "海外") ;
		ipMarkers.put("苏格兰"               , "海外") ;
		ipMarkers.put("南京工业大学"         , "江苏") ;
		ipMarkers.put("成都理工大学"         , "四川") ;
		ipMarkers.put("哈尔滨师范大学"     , "黑龙江") ;
		ipMarkers.put("太原科技大学"         , "山西") ;
		ipMarkers.put("中北大学"             , "山西") ;
		ipMarkers.put("黄河科技大学"         , "河南") ;
		ipMarkers.put("青岛大学"             , "山东") ;
		ipMarkers.put("山东"                 , "山东") ;
		ipMarkers.put("东北大学"             , "辽宁") ;
		ipMarkers.put("南昌大学"             , "江西") ;
		ipMarkers.put("南昌工程学院"         , "江西") ;
		ipMarkers.put("成都中医药大学"       , "四川") ;
		ipMarkers.put("南京化工大学"         , "江苏") ;
		ipMarkers.put("中南大学"             , "湖南") ;
		ipMarkers.put("聚友网络"             , "北京") ;
		ipMarkers.put("武汉科技大学"         , "湖北") ;
		ipMarkers.put("中南财经政法大学"     , "湖北") ;
		ipMarkers.put("西安建筑科技大学"     , "陕西") ;
		ipMarkers.put("西北工业大学"         , "陕西") ;
		ipMarkers.put("青岛科技大学"         , "山东") ;
		ipMarkers.put("河北"                 , "河北") ;
		ipMarkers.put("华北科技学院"         , "北京") ;
		ipMarkers.put("东北农业大学"       , "黑龙江") ;
		ipMarkers.put("哈尔滨工业大学"     , "黑龙江") ;
		ipMarkers.put("暨南大学"             , "广东") ;
		ipMarkers.put("泉州"                 , "福建") ;
		ipMarkers.put("中科院"               , "北京") ;
		ipMarkers.put("西安联合大学"         , "陕西") ;
		ipMarkers.put("南昌理工学院"         , "江西") ;
		ipMarkers.put("成都大学"             , "四川") ;
//		ipMarkers.put("未分配"               , "其他") ;
//		ipMarkers.put("本机地址"             , "北京") ;
//		ipMarkers.put("未知物理地址"         , "其他") ;
//		ipMarkers.put("中国"                 , "北京") ;
//		ipMarkers.put("局域网"               , "北京") ;
//		ipMarkers.put("非公网地址"           , "北京") ;
//		ipMarkers.put("全国"                 , "北京") ;
		ipMarkers.put("联通"                 , "北京") ;
		ipMarkers.put("CNNIC"                , "北京") ;
		ipMarkers.put("长城宽带"             , "北京") ;
		ipMarkers.put("UCWEB手机浏览器"      , "北京") ;
		ipMarkers.put("奇虎qihoo蜘蛛"        , "北京") ;
		                           
		ipMarkers.put("长沙"                 , "湖南") ;
		ipMarkers.put("巴拿马"               , "海外") ;
		ipMarkers.put("华北地区"             , "北京") ;
		ipMarkers.put("华东地区"             , "浙江") ;
		                           
		ipMarkers.put("中央财经大学"         , "北京") ;
		ipMarkers.put("中非共和国"           , "海外") ;
		ipMarkers.put("几内亚"               , "海外") ;
		ipMarkers.put("刚果民主共和国"       , "海外") ;
		ipMarkers.put("利比里亚"             , "海外") ;
		ipMarkers.put("摩尔多瓦共和国"       , "海外") ;
		ipMarkers.put("珠海市"               , "广东") ;
		ipMarkers.put("莱索托"               , "海外") ;
		ipMarkers.put("赤道几内亚"           , "海外") ;
		ipMarkers.put("马拉维"               , "海外") ;
		ipMarkers.put("马里共和国"           , "海外") ;
		ipMarkers.put("澳大利亚"             , "海外") ;
	}
	
	
}
